name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            - name: list files
              run: cat README.md
            - name: welcome message
              run: echo "This is my first github workflows"
            - name: List files
              run: ls -la
            - name: read the file
              run: ls
  
