name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v5
            - name: list files
              run: |
               echo " my first gitlab workflow"
               ls -ltrh
               cat README.md
            - name: generate ASCII artwork
              run: cowsay -f dragon "run for cover, I AM DRAGON.....RAWWWW....." >> dragon.txt 
  
